// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/lib')['ElButton']
    ElConfigProvider: typeof import('element-plus/lib')['ElConfigProvider']
    ElContainer: typeof import('element-plus/lib')['ElContainer']
    ElMain: typeof import('element-plus/lib')['ElMain']
  }
}
